#!/usr/bin/env bash

if [ -z $1 ]; then
    echo "you must provide the temp of the model"
    exit 1
fi

if [ -z $2 ]; then
    go run cmd/main.go --temp $1 --prompt prompt/gencode1.prompt --tf src/challenge.test.js --lang JavaScript --output src/challenge.js -- ./js
else
    go run cmd/main.go --prompt prompt/gencode1.prompt --model $2 --temp $1 --tf src/challenge.test.js --lang JavaScript --output src/challenge.js -- ./js
fi



